#ifndef PBINTERFACE_GLOBAL_H
#define PBINTERFACE_GLOBAL_H
#include "QtCore/qglobal.h"

QT_BEGIN_HEADER
QT_BEGIN_NAMESPACE
QT_MODULE(PBInterface)

#if defined(PBINTERFACE_LIBRARY)
#  define PBINTERFACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define PBINTERFACESHARED_EXPORT Q_DECL_IMPORT
#endif
class PSEUDO_CLASS {
public:
};

QT_END_NAMESPACE
QT_END_HEADER
#endif // PBINTERFACE_GLOBAL_H
