set(CMAKE_BUILD_TYPE Debug)

set(CMAKE_FIND_ROOT_PATH "/srv/einkbuild/SDK2FREE/SDK-481")
list(APPEND CMAKE_MODULE_PATH /srv/einkbuild/SDK2FREE/SDK-481/share/cmake/modules)
list(REMOVE_DUPLICATES CMAKE_MODULE_PATH)
set(QT_QMAKE_EXECUTABLE "/srv/einkbuild/SDK2FREE/SDK-481/local/qt4/bin/qmake")

set(CMAKE_CXX_FLAGS_RELEASE "-DNDEBUG -O2 -pipe -fomit-frame-pointer -march=native -mtune=native " CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE}" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS_RELEASE " -s" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "-s" CACHE STRING "" FORCE)

set(CMAKE_SHARED_LINKER_FLAGS "-Wl,-z,defs" CACHE STRING "" FORCE)

set(CMAKE_CXX_FLAGS_DEBUG "-ggdb -O0 -pipe -fno-omit-frame-pointer" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}" CACHE STRING "" FORCE)
set(CMAKE_EXE_LINKER_FLAGS_DEBUG "" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "" CACHE STRING "" FORCE)

set(CMAKE_INSTALL_PREFIX "/srv/einkbuild/SDK2FREE/SDK-481/local" CACHE PATH "Installation Prefix")
add_definitions(-DEMULATOR -DPLATFORM_NX)

set(PB_PLATFORM "PC" CACHE STRING  "ARM|PC Readonly!")

set(CMAKE_BUILD_TYPE Release CACHE STRING "Debug|Release|RelWithDebInfo|MinSizeRel")
