# -*- cmake -*-

# - Find ObreeySocial library
# Find the ObreeySocial includes and library
# This module defines
# OBREEYSOCIAL_INCLUDE_DIR, where to find g2log.hpp, etc.
# OBREEYSOCIAL_LIBRARIES, the libraries needed to use libsocial.so libbrowser_social.so
# OBREEYSOCIAL_FOUND, If false, do not try to use ObreeySocial.

FIND_PATH(OBREEYSOCIAL_INCLUDE_DIR social_client.h
/include
/usr/include
/usr/local/include
)

FIND_LIBRARY(OBREEYSOCIAL_LIBRARIES
  NAMES libsocial.so libbrowser_social.so
  PATHS /lib /usr/lib /usr/local/lib
)

IF (OBREEYSOCIAL_LIBRARIES AND OBREEYSOCIAL_INCLUDE_DIR)
  SET(OBREEYSOCIAL_FOUND "YES")
ELSE (OBREEYSOCIAL_LIBRARIES AND OBREEYSOCIAL_INCLUDE_DIR)
  SET(OBREEYSOCIAL_FOUND "NO")
ENDIF (OBREEYSOCIAL_LIBRARIES AND OBREEYSOCIAL_INCLUDE_DIR)

IF (OBREEYSOCIAL_FOUND)
  IF (NOT OBREEYSOCIAL_FIND_QUIETLY)
    MESSAGE(STATUS "Found OBREEYSOCIAL: ${OBREEYSOCIAL_LIBRARIES}")
  ENDIF (NOT OBREEYSOCIAL_FIND_QUIETLY)
ELSE (OBREEYSOCIAL_FOUND)
  IF (OBREEYSOCIAL_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find OBREEYSOCIAL library")
  ENDIF (OBREEYSOCIAL_FIND_REQUIRED)
ENDIF (OBREEYSOCIAL_FOUND)
