# -*- cmake -*-

# - Find Common-utilities library
# Find the Inkview includes and library
# This module defines
# UNIVERSAL_SYNC_INCLUDE_DIR, where to find universal_sync.h, etc.
# UNIVERSAL_SYNC_LIBRARIES, the libraries needed to use jsoncpp.
# UNIVERSAL_SYNC_FOUND, If false, do not try to use jsoncpp.

FIND_PATH(UNIVERSAL_SYNC_INCLUDE_DIR universal_sync.h
/include
/usr/include
/usr/local/include
)

FIND_LIBRARY(UNIVERSAL_SYNC_LIBRARIES
  NAMES libuniversal_sync_client.so
  PATHS /lib /usr/lib /usr/local/lib
)

IF (UNIVERSAL_SYNC_LIBRARIES AND UNIVERSAL_SYNC_INCLUDE_DIR)
    SET(UNIVERSAL_SYNC_FOUND "YES")
ELSE (UNIVERSAL_SYNC_LIBRARIES AND UNIVERSAL_SYNC_INCLUDE_DIR)
    SET(UNIVERSAL_SYNC_FOUND "NO")
ENDIF (UNIVERSAL_SYNC_LIBRARIES AND UNIVERSAL_SYNC_INCLUDE_DIR)


IF (UNIVERSAL_SYNC_FOUND)
    IF (NOT UNIVERSAL_SYNC_FIND_QUIETLY)
        MESSAGE(STATUS "Found UNIVERSAL_SYNC_UTILITIES_LIBRARIES}")
    ENDIF (NOT UNIVERSAL_SYNC_FIND_QUIETLY)
ELSE (UNIVERSAL_SYNC_FOUND)
    IF (UNIVERSAL_SYNC_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find UNIVERSAL_SYNC library")
ENDIF (UNIVERSAL_SYNC_FIND_REQUIRED)
ENDIF (UNIVERSAL_SYNC_FOUND)

