# -*- cmake -*-

# - Find Common-utilities library
# Find the Inkview includes and library
# This module defines
# COMMON_UTILITIES_INCLUDE_DIR, where to find json.h, etc.
# COMMON_UTILITIES_LIBRARIES, the libraries needed to use jsoncpp.
# COMMON_UTILITIES_FOUND, If false, do not try to use jsoncpp.

FIND_PATH(COMMON_UTILITIES_INCLUDE_DIR common_utilities
/include
/usr/include
/usr/local/include
)

FIND_LIBRARY(COMMON_UTILITIES_LIBRARIES
  NAMES libcommon_utilities.so
  PATHS /lib /usr/lib /usr/local/lib
)

IF (COMMON_UTILITIES_LIBRARIES AND COMMON_UTILITIES_INCLUDE_DIR)
  SET(COMMON_UTILITIES_FOUND "YES")
ELSE (COMMON_UTILITIES_LIBRARIES AND COMMON_UTILITIES_INCLUDE_DIR)
  SET(COMMON_UTILITIES_FOUND "NO")
ENDIF (COMMON_UTILITIES_LIBRARIES AND COMMON_UTILITIES_INCLUDE_DIR)


IF (COMMON_UTILITIES_FOUND)
  IF (NOT COMMON_UTILITIES_FIND_QUIETLY)
    MESSAGE(STATUS "Found COMMON_UTILITIES: ${COMMON_UTILITIES_LIBRARIES}")
  ENDIF (NOT COMMON_UTILITIES_FIND_QUIETLY)
ELSE (COMMON_UTILITIES_FOUND)
  IF (COMMON_UTILITIES_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find COMMON_UTILITIES library")
  ENDIF (COMMON_UTILITIES_FIND_REQUIRED)
ENDIF (COMMON_UTILITIES_FOUND)
