# -*- cmake -*-

# - Find PBFramework2 library
# Find the Inkview includes and library
# This module defines
# PBFRAMEWORK2_INCLUDE_DIR, where to find json.h, etc.
# PBFRAMEWORK2_LIBRARIES, the libraries needed to use jsoncpp.
# PBFRAMEWORK2_FOUND, If false, do not try to use jsoncpp.

FIND_PATH(PBFRAMEWORK2_INCLUDE_DIR pbframework-2
/include
/usr/include
/usr/local/include
)

FIND_LIBRARY(PBFRAMEWORK2_LIBRARIES
  NAMES libframework2.so
  PATHS /lib /usr/lib /usr/local/lib
)

IF (PBFRAMEWORK2_LIBRARIES AND PBFRAMEWORK2_INCLUDE_DIR)
  SET(PBFRAMEWORK2_FOUND "YES")
ELSE (PBFRAMEWORK2_LIBRARIES AND PBFRAMEWORK2_INCLUDE_DIR)
  SET(PBFRAMEWORK2_FOUND "NO")
ENDIF (PBFRAMEWORK2_LIBRARIES AND PBFRAMEWORK2_INCLUDE_DIR)


IF (PBFRAMEWORK2_FOUND)
  IF (NOT PBFRAMEWORK2_FIND_QUIETLY)
    MESSAGE(STATUS "Found PBFramework2: ${PBFRAMEWORK2_LIBRARIES}")
  ENDIF (NOT PBFRAMEWORK2_FIND_QUIETLY)
ELSE (PBFRAMEWORK2_FOUND)
  IF (PBFRAMEWORK2_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find PBFramework2 library")
  ENDIF (PBFRAMEWORK2_FIND_REQUIRED)
ENDIF (PBFRAMEWORK2_FOUND)
